config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  get 'users/new', to: 'posts#new', as: 'new'
  post 'users/new', to: 'posts#create', as: 'create_post'
  root 'users#index'
  resources :users, only: [:index, :show] do
    resources :posts
  end
  resources :comments, only: [:destroy]
  post 'comments/:id', to: 'comments#create', as: 'create_comment'

  post 'likes/:id', to: 'likes#create', as: 'create_like'

  namespace :api do
    namespace :v1 do

      resources :users do
        resources :posts do
          resources :comments
        end
      end
      
      root 'users#index'
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all
    can :create, :all
    can :destroy, Post, author_id: user.id
    can :destroy, Comment, author_id: user.id
    can :manage, :all if user.role == 'admin'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :surname, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :surname, :email, :password, :current_password)
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, foreign_key: 'post_id'
  has_many :likes, foreign_key: 'post_id'
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }

  def five_most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def update_likes_counter
    update(likes_counter: likes.count)
  end

  def update_comments_counter
    update(comments_counter: comments.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable # , :confirmable
  has_many :posts, foreign_key: 'author_id'
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }

  def three_most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def update_posts_counter
    update(posts_counter: posts.count)
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |_exception|
    redirect_to root_path, notice: 'Access denied'
  end

  def create
    @new_comment = Comment.new(comment_params)
    @new_comment.post = Post.find(params[:id])
    @new_comment.author = current_user

    if @new_comment.save
      render json: @new_comment, status: :created, location: @new_comment
    else
      render json: @new_comment.errors, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  layout 'standard'

  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |_exception|
    redirect_to root_path, notice: 'Access denied'
  end

  def index
    @user = User.includes(:posts).find(params[:user_id])
    @posts = Post.where(author: @user)
    render json: @posts, status: :ok, only: %i[id author_id title text]
  end

  def show
    @comments = Comment.where(post: @post.id)
    render json: @post.comments, status: :ok, only: %i[id author_id post_id text]
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  layout 'standard'
  def index
    @users = User.all
    render json: @users, status: :ok, only: %i[id name]
  end

  def show
    @user = User.find(params[:id])
    render json: @user, status: :ok, only: %i[id name bio photo]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |_exception|
    redirect_to root_path, notice: 'Access denied'
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to request.referrer, notice: 'Comment was successfully deleted.'
  end

  def create
    @new_comment = Comment.new(comment_params)
    @new_comment.post = Post.find(params[:id])
    @new_comment.author = current_user

    @new_comment.save
    redirect_to request.referrer
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @new_like = Like.new
    @new_like.post = Post.find(params[:id])
    @new_like.author = current_user

    @new_like.save
    # Redirect to the same page
    redirect_to request.referrer
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout 'standard'

  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |_exception|
    redirect_to root_path, notice: 'Access denied'
  end

  def index
    @user = User.includes(:posts).find(params[:user_id]) # N+1
    @user.update_posts_counter
    @posts = Post.where(author: @user)
    @posts.each do |post|
      post.update_comments_counter
      post.update_likes_counter
    end
    render status: 200

    respond_to do |format|
      format.html
      format.xml { render xml: @posts }
      format.json { render json: @posts }
    end
  end

  def show
    @new_comment = Comment.new
    @new_like = Like.new

    @post = Post.includes(:comments).find(params[:id]) # N+1
    @post.update_comments_counter
    @post.update_likes_counter
    @user = @post.author
    @comments = Comment.where(post: @post.id)
    render status: 200

    respond_to do |format|
      format.html
      format.xml { render xml: @post.comments }
      format.json { render json: @post.comments }
    end
  end

  def new
    @new_post = Post.new
    @user = current_user
  end

  def create
    @new_post = Post.new(post_params)
    @new_post.author = current_user
    if @new_post.save
      flash[:notice] = 'Post created!'
      redirect_to "/users/#{current_user.id}/posts/#{@new_post.id}"
    else
      flash[:notice] = @new_post.errors.full_messages.join(', ')
      redirect_to request.referrer
    end
  end

  def destroy
    @del_post = Post.find(params[:id])
    @post_comments = @del_post.comments
    @post_comments.destroy_all
    @post_likes = @del_post.likes
    @post_likes.destroy_all
    @del_post.destroy
    redirect_to users_path, notice: 'Post was successfully destroyed.'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'standard'
  def index
    @users = User.all
    @users.each(&:update_posts_counter)
    render status: 200
  end

  def show
    @user = User.includes(:posts).find(params[:id]) # N+1
    @user.update_posts_counter
    @posts = @user.three_most_recent_posts
    @posts.each do |post|
      post.update_comments_counter
      post.update_likes_counter
    end
    render status: 200
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/standard.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns = "http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv = "Content-Type" content = "text/html; charset = iso-8859-1" />
    <meta http-equiv = "Content-Language" content = "en-us" />
    <title>i Blog</title>
    <%= stylesheet_link_tag "style" %>
  </head>
  <body>
    <div class = "container">
      <header>
        <%= link_to users_path do %>
          <h1>i Bolg</h1>
        <% end %>
      </header>
      <h2>My Username: <%= current_user.name%></h2>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div class = "content">
        <%= yield -%>
      </div>
      <footer>Some rights reserved</footer>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<h2>List of Posts</h2>
<%= render partial: "shared/user_card", locals: { user: @user } %>
<div class="posts-list">
  <% @posts.each do |post|%>
    <section class = "post-info">
      <%= render partial: "shared/post_card", locals: { post: post } %>
      <% comments = post.five_most_recent_comments %>
      <% comments.each do |comment|%>
        <% user = User.find(comment.author_id)%>
        <%= render partial: "shared/comment", locals: { comment: comment, user: user } %>
      <%end%>
    </section>
  <%end%>
  <button type="button">Pagination</button>
</div>

app/views/posts/new.html.erb
<h2>New post is being created by <i> <%= @user.name %> </i> </h2>
<%= form_with model: @new_post, url: create_post_path do |form| %>
<%puts 'Log>>'%>
<%puts create_post_path%>
  <%= form.label :title %>: 
  <%= form.text_field :title %><br>
  <%= form.text_area :text, size: "70x5" %><br>
  <%= form.submit "Create Post" %>
<% end %>
<% if flash[:error] %>
  <div class="error-message">
    <%= flash[:error] %>
  </div>
<% end %>

app/views/posts/show.html.erb
<h2>Post</h2>
<div class="post-container">
  <%= render partial: "shared/post", locals: { post: @post, user: @user} %>
  <%= render partial: "shared/comment_like_form"%>
  <% @comments.each do |comment|%>
    <% user = User.find(comment.author_id)%>
    <%= render partial: "shared/comment", locals: { comment: comment, user: user } %>
  <%end%>
</div>
<br/>
<% if can? :destroy, @post %>
  <%= button_to "Destroy this post", @del_post, method: :delete %> <%# didn't use path coz the destroy method of the post is in the same controller%>
<% end %>

app/views/shared/_comment.html.erb
<div class="comment">
  <h4 class="commentor"><%= user.name%>: </h4>
  <p><%= comment.text%></p>
<% if can? :destroy, comment %>
  <%# used path coz the destroy method of the comment is not in the same controller of post#show, and needs route%>
  <%= button_to "Destroy this comment", comment_path(comment), method: :delete %> <%# we can use only (comment) instead of (comment.id) and rails will understand%>
<% end %>

</div>

app/views/shared/_comment_like_form.html.erb
<div class="comment-like-form-container">
  <%= form_with model: @new_comment, url: create_comment_path(@post), class: "ignored" do |form| %>
    <%= form.text_area :text, size: "70x5", class: "comment-field" %><br>
    <%= form.submit "Comment", class: "comment-btn" %>
  <% end %>
  <%= form_with model: @new_like, url: create_like_path(@post), class: "ignored" do |form| %>
    <%= form.submit "Like", class: "like-btn" %>
  <% end %>
</div>

app/views/shared/_post.html.erb
<div class="post">
  <section class="post-header">
    <h3 class="title"><%= post.title%> <i> by <%= user.name%> </i> </h3>
    <span class="counters">Comments: <%= post.comments_counter%>, Likes: <%= post.likes_counter%></span>
  </section>
  <p class="text"><%= post.text%></p>
</div>

app/views/shared/_post_card.html.erb
<%= link_to user_post_path(user_id: post.author_id, id: post.id ) do %>
  <div class="post-card">
    <h3 class="title"><%= post.title%></h3>
    <p><%= truncate(post.text, length: 100)%></p>
    <span class="counters">Comments: <%= post.comments_counter%>, Likes: <%= post.likes_counter%></span>
  </div>
<% end %>

app/views/shared/_user_card.html.erb
<%= link_to user_path(user.id) do %>
  <div class="user-card">
    <img src="<%= user.photo %>" alt="User Photo" class="user-img">
    <section class="info">
      <h3 class="name"><%= user.name%></h3>
      <span class="posts-num">Number of posts: <%= user.posts_counter%></span>
    </section>
  </div>
<% end %>

app/views/users/index.html.erb
<h2>List of Users</h2>
<% @users.each do |user|%>
  <%= render partial: "shared/user_card", locals: { user: user } %>
<%end%>
<%= link_to "Create New Post", new_path, class: "new-post-btn"%>
|
<%= link_to "Sign out", destroy_user_session_path, class: "btn"%>

app/views/users/show.html.erb
<h2>User's Page</h2>
<%= render partial: "shared/user_card", locals: { user: @user } %>
<div class="user-info">
  <section class="bio">
    <h3>Bio</h3>
    <p><%= @user.bio%></p>
  </section>
  <section class="posts-list">
    <% @posts.each do |post|%>
      <%= render partial: "shared/post_card", locals: { post: post } %>
    <%end%>
  </section>
  <%= link_to "See all posts", user_posts_path(user_id: @user.id), class: "all-posts-btn"%>
</div>